#!/usr/bin/env bash

# Create our VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc}]' \
--region us-east-1 \
--query Vpc.VpcId \
--output text)

echo "VPC_ID: $VPC_ID"

# Turn on DNS Hostnames
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\":true}"

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=my-igw}]' \
--output text \
--query InternetGateway.InternetGatewayId)

echo "IGW_ID: $IGW_ID"

# Attach an IGW
aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

echo "$IGW_ID attached to $VPC_ID"

# Create new Subnets
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 172.1.0.0/20 \
--tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=my-subnet-1}]' \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID: $SUBNET_ID"

# Auto assign IPv4 Addresses
aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID \
--map-public-ip-on-launch

# Explicitly Associate subnets
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query RouteTables[].RouteTableId \
--output text
)

echo "RT_ID: $RT_ID"

ASSOCIATION_STATE=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--output text \
--query AssociationState.State
)

echo "$SUBNET_ID $ASSOCIATION_STATE with $RT_ID"

# Add a route for out RT to our IGW
echo "External Internet Route Created: $(aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID \
--output text \
--query Return)"

# Print out Delete Command
echo ""
echo "Destroy Command:"
echo "./delete_vpc $VPC_ID $IGW_ID $SUBNET_ID $RT_ID"