#!/usr/bin/env bash

# VPC IGW SUBNET RT

if [ -z "$1" ]; then
  echo "Argument not provided"
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "Argument not provided"
else
  export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "Argument not provided"
else
  export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "Argument not provided"
else
  export RT_ID="$4"
fi

# Detach IGW
aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

echo "IGW Detached..."

# Delete IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

echo "IGW Deleted."

# Disassociate Subnet from IGW
ASSOC_ID=$(aws ec2 describe-route-tables \
--route-table-ids $RT_ID \
--filters "Name=association.subnet-id,Values=$SUBNET_ID" \
--query "RouteTables[].Associations[?SubnetId=='$SUBNET_ID'].RouteTableAssociationId[]" \
--output text)

aws ec2 disassociate-route-table --association-id $ASSOC_ID

echo "Subnet Disassociated..."

# Delete Subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

echo "Subnet Deleted."

# Delete VPC
aws ec2 delete-vpc --vpc-id $VPC_ID

echo "VPC Deleted"

# Closing Message
echo ""
echo "Destroy Complete"
